export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const ADD = 'ADD'
export const INCREMENT_REQ = 'INCREMENT_REQ'
export const DECREMENT_REQ = 'DECREMENT_REQ'
export const ADD_REQ = 'ADD_REQ'
